logging:
  path: ./logs

spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/school?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&autoReconnect=true&amp
      username: growlithe
      password: growlithe



#  http:
#    multipart:
#      max-file-size: 20Mb
#      max-request-size: 100Mb

#
#attachment:
#  path:  /Users/wangxin/
